name: pita
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - hydra-core>=1.3.2
      - omegaconf>=2.3.0
      - numpy>=2.1.0
      - pandas>=2.2.0
      - matplotlib>=3.9.0
      - rich>=13.9.0
      - loguru>=0.7.0
      - tqdm>=4.66.0

      - datasets>=3.0.2
      - transformers>=4.47.0
      - torch>=2.4.1
      - pyarrow>=18.0.0
      - sentencepiece>=0.2.0
      - accelerate>=0.30.0
