name: pita
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - numpy==1.26.4
      - pandas==2.2.3
      - matplotlib==3.9.2
      - rich==13.9.2
      - loguru==0.7.2
      - tqdm==4.66.5

      - datasets==3.0.2
      - transformers==4.45.2
      - torch==2.4.1
