experiment:
  name: Llama_8B_Base_Eval
  seed: 42
rounds_of_training: 0
resume_from: null
system:
  dtype: bfloat16
  amp_dtype: bfloat16
  attn_impl: sdpa
  clear_cache_interval: 10
generation:
  max_new_tokens: 1024
  temperature: 0.8
  top_p: 0.9
  use_chat_template: true
training:
  micro_batch_size: 4
  gradient_checkpointing: true
  datasets:
  - GSM8K
  # - IMDBGen
  # - TLDR
  # - MATH
  # - AIME22to24
data_collection:
  samples_per_example: 2
  seed: 42
  reward_batch_size: 64
  chunk_size: 32
  bradley_terry_sampling: true
  bradley_terry_beta: 1.0
evaluation:
  etas:
  - 1.0
  num_samples: 8
  batch_size: 16
  kl_sample_ratio: 0.1
  datasets_by_train:
    GSM8K:
    - GSM8K
    TLDR:
    - TLDR
    IMDBGen:
    - IMDBGen
    MATH:
    - MATH
    AIME22to24:
    - AIME22to24
parallel_generation: false
use_parallel_execution: true
algos: {}
model_pairs:
- llama-old
datasets:
  AIME2025:
    train_size_cap: 0
    test_size_cap: 0
    train_hf_config: AIME2025-II
    train_split: test
    question_key: question
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: AIME2025-II
    test_split: heldout
  AIME2024:
    train_size_cap: 0
    test_size_cap: 0
    train_hf_config: default
    train_split: train
    question_key: problem
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: default
    test_split: heldout
  GSM8K:
    train_size_cap: 0
    test_size_cap: 0
    train_hf_config: main
    train_split: train
    question_key: question
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: main
    test_split: heldout
  TLDR:
    train_size_cap: 0
    test_size_cap: 0
    train_hf_config: ''
    train_split: train
    question_key: prompt
    answer_key: completion
    reward_model: OpenAssistant/reward-model-deberta-v3-large-v2
    test_hf_config: ''
    test_split: test
  IMDBGen:
    train_size_cap: 0
    test_size_cap: 5000
    train_hf_config: ''
    train_split: train
    question_key: text
    answer_key: label
    reward_model: lvwerra/distilbert-imdb
    test_hf_config: ''
    test_split: test
  MATH:
    train_size_cap: 0
    test_size_cap: 0
    train_hf_config: ''
    train_split: test
    question_key: problem
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: ''
    test_split: heldout
  AIME22to24:
    train_size_cap: 0
    test_size_cap: 0
    train_hf_config: default
    train_split: train
    question_key: problem
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: default
    test_split: heldout
