experiment:
  name: gemma_trial
  seed: 42
rounds_of_training: 1
resume_from: null
system:
  dtype: bfloat16
  amp_dtype: bfloat16
  attn_impl: eager
  clear_cache_interval: 10
generation:
  max_new_tokens: 1024
  temperature: 0.8
  top_p: 0.9
  use_chat_template: true
training:
  micro_batch_size: 4
  gradient_checkpointing: true
  datasets:
  - GSM8K
data_collection:
  samples_per_example: 4
  seed: 42
  max_examples: 2500
  reward_batch_size: 64
  chunk_size: 128
  bradley_terry_sampling: true
  bradley_terry_beta: 1.0
evaluation:
  etas:
  - 0.25
  - 0.5
  - 1.0
  - 4.0
  num_samples: 8
  batch_size: 32
  max_examples: 250
  kl_sample_ratio: 0.1  # 10% of examples for approximate KL
  datasets_by_train:
    GSM8K:
    - GSM8K
    - MATH
    - AIME
    TLDR:
    - TLDR
    IMDBGen:
    - IMDBGen
parallel_generation: false
use_parallel_execution: true
algos:
  PITA:
    epochs: 10
    batch_size: 32
    eval_batch_size: 32
    max_batch_num_tokens: 16384
    num_workers: 4
    lr: 2.0e-05
    weight_decay: 0.0
    grad_clip: 1.0
    loss_type: bce
    num_atoms: 11
    V_min: 0.0
    V_max: 1.0
    guidance:
      eta: 1.0
      mode: bernoulli
      top_k: 20
      use_cache: false
  QSharp:
    epochs: 10
    batch_size: 32
    eval_batch_size: 32
    max_batch_num_tokens: 16384
    num_workers: 4
    lr: 2.0e-05
    weight_decay: 0.0
    grad_clip: 1.0
    loss_type: bce
    num_atoms: 11
    V_min: 0.0
    V_max: 1.0
    guidance:
      eta: 1.0
      mode: bernoulli
      top_k: 20
      use_cache: false
  QSharp-HF:
    epochs: 10
    proxy_epochs: 5
    batch_size: 32
    eval_batch_size: 32
    max_batch_num_tokens: 16384
    num_workers: 4
    lr: 2.0e-05
    proxy_lr: 2.0e-05
    weight_decay: 0.0
    grad_clip: 1.0
    proxy_loss_type: bradley_terry
    loss_type: mle
    num_atoms: 11
    V_min: 0.0
    V_max: 1.0
    guidance:
      eta: 1.0
      mode: expectation
      top_k: 20
      use_cache: false
  # DPO, GRPO, GRPO-HF removed due to OOM issues
model_pairs:
- gemma
- llama
datasets:
  AIME:
    train_hf_config: AIME2025-I
    train_split: test
    question_key: question
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: AIME2025-I
    test_split: test
  GSM8K:
    train_hf_config: main
    train_split: train
    question_key: question
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: main
    test_split: test
  TLDR:
    train_hf_config: ''
    train_split: train
    question_key: prompt
    answer_key: completion
    reward_model: OpenAssistant/reward-model-deberta-v3-large-v2
    test_hf_config: ''
    test_split: test
  IMDBGen:
    train_hf_config: ''
    train_split: train
    question_key: text
    answer_key: label
    reward_model: lvwerra/distilbert-imdb
    test_hf_config: ''
    test_split: test
  MATH:
    train_hf_config: ''
    train_split: test
    question_key: problem
    answer_key: answer
    reward_model: weqweasdas/RM-Gemma-2B
    test_hf_config: ''
    test_split: test
